<%
var getFiles = function(prop) {return grunt.file.expand({cwd:'.'},grunt.config.get(prop));};
%>//----------------------------------------------------------------------------------------------------------------------
// This is an autogenerated file containing the contents of all the controller javascript for all components.
//
// @module client.controllers.js
//----------------------------------------------------------------------------------------------------------------------

var module = angular.module('components.controllers', []);

<% _.forEach(getFiles('project.components.controllers'), function(src) { var file = grunt.file.read(src); %>
/* ====================== Begin: <%= src %> ====================== */

<%= file %>

/* ======================  End: <%= src %>  ====================== */
<% }); %>

//----------------------------------------------------------------------------------------------------------------------